name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Check for bug keyword'
      id: check_bug
      uses: actions/github-script@v7
      with:
        script: |
          const title = context.payload.issue?.title || context.payload.pull_request?.title || '';
          const body = context.payload.issue?.body || context.payload.pull_request?.body || '';
          core.setOutput('has_bug', /bug/i.test(title + ' ' + body));
    - name: 'Auto-assign issue if bug'
      if: steps.check_bug.outputs.has_bug == 'true'
      uses: pozil/auto-assign-issue@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: Lucas04-nhr
        numOfAssignee: 1